### ISSUE TITLE
Add a Unit Test Job to the pipeline

### ISSUE THREAD

**Issue by xxiao626** [products-devops-fall-21/products#109]
**As a** developer
**I need** to run units tests with nosetests
**So that** the cloud could deploy the app

**Details & Assumptions:** 
* Build Stage has been added to the pipeline

**Acceptance Criteria:**

```gherkin
When the units tests pass
Then the pipeline continue the Devp Stage
```

**Comment by sonawanemaitreya** [comment]
Added nosetests in build stage and it is running
