### ISSUE TITLE
Add a Integration Test Stage to the pipeline

### ISSUE THREAD

**Issue by xxiao626** [products-devops-fall-21/products#110]
**As a** Developer
**I need** a Test Stage to run integration tests with behave
**So that** the cloud could deploy the app

**Details & Assumptions:** 
* Dev Stage has deployed the Dev space when the unit tests pass

**Acceptance Criteria:**

```gherkin
When the integration tests pass
Then the pipeline continue the Prod Stage
```

**Comment by sonawanemaitreya** [comment]
Added the Test stage in pipeline
