### ISSUE TITLE
Add a Production Deploy Stage to the pipeline

### ISSUE THREAD

**Issue by xxiao626** [products-devops-fall-21/products#111]
**As a** Developer
**I need** Prod Stage to deploy the production space
**So that** the cloud could deploy the app

**Details & Assumptions:** 
* The new space in the Cloud Foundry account has been built

**Acceptance Criteria:**

```gherkin
When all integration tests pass
Then we could deploy the production space
```

**Comment by sonawanemaitreya** [comment]
Production app is deployed to https://nyu-product-service-fall2103-production.us-south.cf.appdomain.cloud/
